services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://cryptoplace.kusmicrew.cloud/api
      - VITE_XRPL_NODE=wss://s.altnet.rippletest.net:51233
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:ro
      - ./data:/data
      - ./data/uploads:/data/uploads
      - session-data:/tmp/flask_session
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_PATH=/data/crypto.db
      - PYTHONPATH=/app
      - XRPL_NODE=wss://s.altnet.rippletest.net:51233
    env_file:
      - ./backend/.env
    depends_on:
      - xrpl_setup
    networks:
      - internal

  xrpl_setup:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./xrpl-setup:/app
      - ./data:/data
    command: >
      sh -c "npm install xrpl &&
             node setup-test-accounts.js"
    environment:
      - XRPL_NODE=wss://s.altnet.rippletest.net:51233
    networks:
      - internal

networks:
  internal:
    driver: bridge
    driver_opts:
      encrypted: "true"

volumes:
  session-data:
