"""Updated db

Revision ID: c8d75384c9ba
Revises: 5619c1bf66d9
Create Date: 2024-12-22 14:29:21.869498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d75384c9ba'
down_revision = '5619c1bf66d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xrpl_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xrpl_balance')

    # ### end Alembic commands ###
