"""token_id mod and cascade added to listings

Revision ID: fa35054c23ca
Revises: c8d75384c9ba
Create Date: 2025-01-05 12:03:21.078026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35054c23ca'
down_revision = 'c8d75384c9ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_token_id'), ['token_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_token_id'))

    # ### end Alembic commands ###
