name: Deploy on VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Copy code to the remote VM over SCP
      - name: Copy code to remote VM
        uses: appleboy/scp-action@v0.1.9
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "./"
          target: "/home/ubuntu/my_app"   # Modify path to your desired directory
          overwrite: true

      # 3. SSH into the VM and run commands
      - name: SSH and run commands on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /home/ubuntu/my_app
            # Example commands:
            # 1. Install dependencies
            npm install
            # 2. Build or run your application
            npm run build
            npm start